#!/usr/bin/env ruby
# example v3.2.15
# ./rails-doc v3.2.15
tag = ARGV.first
abort("please pass a tag - eg. v3.2.15") unless tag
`cd rails && git co #{tag} && cd ..`
`bundle exec sdoc --fmt sdoc --debug --github -x test -x example -x bin -N --main rails/README.rdoc --title "Rails #{tag}" --op "rails-#{tag}" rails`
`cd rails && git co master && cd ..`
